site_name: hsv_dot_beer
site_description: Collate ALL the Huntsville beers
repo_url: https://github.com/hsv-dot-beer/hsvdotbeer
site_dir: site
copyright: Copyright &copy; 2018-19, <a href="https://github.com/hsv-dot-beer">hsv-dot-beer</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Getting Started: 'api/getting_started.md'
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
    - Venues: 'venues/venues.md'
    - Beers: 'beers/beers.md'
    - Manufacturers: 'beers/manufacturers.md'
  - Tap List Providers:
    - Parsers: 'tap_list_providers/parsers.md'
